// Material Data (Auto Generated)
const MATERIAL_DEFINITIONS = {
    "300001":  {
                   "id":  300001,
                   "type":  "ore",
                   "name":  "구리 광석",
                   "rarity":  "D",
                   "description":  "가장 기본적인 광석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#B87333",
                   "returnGoldValue":  2
               },
    "300002":  {
                   "id":  300002,
                   "type":  "ore",
                   "name":  "철 광석",
                   "rarity":  "C",
                   "description":  "단단한 철 광석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#708090",
                   "returnGoldValue":  6
               },
    "300003":  {
                   "id":  300003,
                   "type":  "ore",
                   "name":  "은 광석",
                   "rarity":  "B",
                   "description":  "은빛 광택의 광석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#C0C0C0",
                   "returnGoldValue":  20
               },
    "300004":  {
                   "id":  300004,
                   "type":  "ore",
                   "name":  "금 광석",
                   "rarity":  "A",
                   "description":  "귀중한 금 광석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  60
               },
    "300005":  {
                   "id":  300005,
                   "type":  "ore",
                   "name":  "미스릴 광석",
                   "rarity":  "S",
                   "description":  "신비로운 광석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#9370DB",
                   "returnGoldValue":  200
               },
    "300006":  {
                   "id":  300006,
                   "type":  "ore",
                   "name":  "오리하르콘",
                   "rarity":  "SS",
                   "description":  "전설의 금속",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#00CED1",
                   "returnGoldValue":  600
               },
    "300007":  {
                   "id":  300007,
                   "type":  "ore",
                   "name":  "드래곤 광석",
                   "rarity":  "SR",
                   "description":  "드래곤에게서 얻은 광석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  2000
               },
    "300008":  {
                   "id":  300008,
                   "type":  "ore",
                   "name":  "신의 금속",
                   "rarity":  "SU",
                   "description":  "신이 내린 금속",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  6000
               },
    "300101":  {
                   "id":  300101,
                   "type":  "herb",
                   "name":  "약초",
                   "rarity":  "D",
                   "description":  "기본적인 치료용 약초",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#228B22",
                   "returnGoldValue":  2
               },
    "300102":  {
                   "id":  300102,
                   "type":  "herb",
                   "name":  "푸른 약초",
                   "rarity":  "C",
                   "description":  "청량한 기운의 약초",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#00FF7F",
                   "returnGoldValue":  6
               },
    "300103":  {
                   "id":  300103,
                   "type":  "herb",
                   "name":  "붉은 약초",
                   "rarity":  "B",
                   "description":  "활력을 주는 약초",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FF6347",
                   "returnGoldValue":  20
               },
    "300104":  {
                   "id":  300104,
                   "type":  "herb",
                   "name":  "황금 약초",
                   "rarity":  "A",
                   "description":  "희귀한 황금빛 약초",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  60
               },
    "300105":  {
                   "id":  300105,
                   "type":  "herb",
                   "name":  "신비의 꽃",
                   "rarity":  "S",
                   "description":  "마력이 깃든 꽃",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#9370DB",
                   "returnGoldValue":  200
               },
    "300106":  {
                   "id":  300106,
                   "type":  "herb",
                   "name":  "세계수 잎",
                   "rarity":  "SS",
                   "description":  "세계수에서 떨어진 잎",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#00FF7F",
                   "returnGoldValue":  600
               },
    "300107":  {
                   "id":  300107,
                   "type":  "herb",
                   "name":  "드래곤 허브",
                   "rarity":  "SR",
                   "description":  "드래곤의 숨결이 깃든 약초",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  2000
               },
    "300108":  {
                   "id":  300108,
                   "type":  "herb",
                   "name":  "신의 축복",
                   "rarity":  "SU",
                   "description":  "신성한 기운의 약초",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  6000
               },
    "300201":  {
                   "id":  300201,
                   "type":  "leather",
                   "name":  "낡은 가죽",
                   "rarity":  "D",
                   "description":  "품질이 낮은 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#8B4513",
                   "returnGoldValue":  2
               },
    "300202":  {
                   "id":  300202,
                   "type":  "leather",
                   "name":  "질긴 가죽",
                   "rarity":  "C",
                   "description":  "튼튼한 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#A0522D",
                   "returnGoldValue":  6
               },
    "300203":  {
                   "id":  300203,
                   "type":  "leather",
                   "name":  "고급 가죽",
                   "rarity":  "B",
                   "description":  "부드럽고 질긴 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#D2691E",
                   "returnGoldValue":  20
               },
    "300204":  {
                   "id":  300204,
                   "type":  "leather",
                   "name":  "마수 가죽",
                   "rarity":  "A",
                   "description":  "마물에게서 얻은 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#800000",
                   "returnGoldValue":  60
               },
    "300205":  {
                   "id":  300205,
                   "type":  "leather",
                   "name":  "드래곤 가죽",
                   "rarity":  "S",
                   "description":  "드래곤 비늘 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  200
               },
    "300206":  {
                   "id":  300206,
                   "type":  "leather",
                   "name":  "고대 가죽",
                   "rarity":  "SS",
                   "description":  "고대 마수의 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#4B0082",
                   "returnGoldValue":  600
               },
    "300207":  {
                   "id":  300207,
                   "type":  "leather",
                   "name":  "천룡 가죽",
                   "rarity":  "SR",
                   "description":  "천룡의 비늘 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#00CED1",
                   "returnGoldValue":  2000
               },
    "300208":  {
                   "id":  300208,
                   "type":  "leather",
                   "name":  "신수 가죽",
                   "rarity":  "SU",
                   "description":  "신수의 성스러운 가죽",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  6000
               },
    "300301":  {
                   "id":  300301,
                   "type":  "wood",
                   "name":  "나뭇가지",
                   "rarity":  "D",
                   "description":  "흔한 나뭇가지",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#8B7355",
                   "returnGoldValue":  2
               },
    "300302":  {
                   "id":  300302,
                   "type":  "wood",
                   "name":  "단단한 목재",
                   "rarity":  "C",
                   "description":  "가공된 목재",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#DEB887",
                   "returnGoldValue":  6
               },
    "300303":  {
                   "id":  300303,
                   "type":  "wood",
                   "name":  "마력 목재",
                   "rarity":  "B",
                   "description":  "마력이 스민 나무",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#9370DB",
                   "returnGoldValue":  20
               },
    "300304":  {
                   "id":  300304,
                   "type":  "wood",
                   "name":  "세계수 가지",
                   "rarity":  "A",
                   "description":  "세계수의 가지",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#00FF7F",
                   "returnGoldValue":  60
               },
    "300305":  {
                   "id":  300305,
                   "type":  "wood",
                   "name":  "정령목",
                   "rarity":  "S",
                   "description":  "정령이 깃든 나무",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#7CFC00",
                   "returnGoldValue":  200
               },
    "300306":  {
                   "id":  300306,
                   "type":  "wood",
                   "name":  "신목",
                   "rarity":  "SS",
                   "description":  "신성한 나무",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  600
               },
    "300307":  {
                   "id":  300307,
                   "type":  "wood",
                   "name":  "용목",
                   "rarity":  "SR",
                   "description":  "드래곤의 기운이 깃든 나무",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  2000
               },
    "300308":  {
                   "id":  300308,
                   "type":  "wood",
                   "name":  "생명의 나무",
                   "rarity":  "SU",
                   "description":  "생명력이 넘치는 신목",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  6000
               },
    "300401":  {
                   "id":  300401,
                   "type":  "gem",
                   "name":  "조각난 보석",
                   "rarity":  "D",
                   "description":  "깨진 보석 조각",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#ADD8E6",
                   "returnGoldValue":  3
               },
    "300402":  {
                   "id":  300402,
                   "type":  "gem",
                   "name":  "루비 원석",
                   "rarity":  "C",
                   "description":  "붉은 보석 원석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#DC143C",
                   "returnGoldValue":  10
               },
    "300403":  {
                   "id":  300403,
                   "type":  "gem",
                   "name":  "사파이어 원석",
                   "rarity":  "B",
                   "description":  "푸른 보석 원석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#0000FF",
                   "returnGoldValue":  30
               },
    "300404":  {
                   "id":  300404,
                   "type":  "gem",
                   "name":  "에메랄드 원석",
                   "rarity":  "A",
                   "description":  "초록 보석 원석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#50C878",
                   "returnGoldValue":  100
               },
    "300405":  {
                   "id":  300405,
                   "type":  "gem",
                   "name":  "다이아몬드 원석",
                   "rarity":  "S",
                   "description":  "최고급 보석 원석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#E0FFFF",
                   "returnGoldValue":  300
               },
    "300406":  {
                   "id":  300406,
                   "type":  "gem",
                   "name":  "용의 눈",
                   "rarity":  "SS",
                   "description":  "드래곤의 눈 보석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  1000
               },
    "300407":  {
                   "id":  300407,
                   "type":  "gem",
                   "name":  "세계의 결정",
                   "rarity":  "SR",
                   "description":  "세계의 힘이 담긴 결정",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#9370DB",
                   "returnGoldValue":  3000
               },
    "300408":  {
                   "id":  300408,
                   "type":  "gem",
                   "name":  "창조의 보석",
                   "rarity":  "SU",
                   "description":  "창조의 힘이 담긴 보석",
                   "stackMax":  999,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  10000
               }
};
