// Monster ?곗씠??(?먮룞 ?앹꽦??
const MONSTER_DATA = [
    {
        "id":  100001,
        "expGain":  20,
        "coinValue":  10,
        "hp":  50,
        "name":  "슬라임",
        "type":  "slime",
        "equipDropChance":  0.5,
        "damage":  10,
        "height":  36,
        "isHpBig":  false,
        "coinCount":  2,
        "maxRarity":  "SU",
        "width":  40,
        "speed":  1.5
    },
    {
        "id":  100002,
        "expGain":  35,
        "coinValue":  15,
        "hp":  80,
        "name":  "버섯",
        "type":  "mushroom",
        "equipDropChance":  0.5,
        "damage":  15,
        "height":  44,
        "isHpBig":  false,
        "coinCount":  3,
        "maxRarity":  "SU",
        "width":  36,
        "speed":  1
    },
    {
        "id":  100003,
        "expGain":  45,
        "coinValue":  20,
        "hp":  60,
        "name":  "유령",
        "type":  "ghost",
        "equipDropChance":  0.5,
        "damage":  20,
        "height":  46,
        "isHpBig":  false,
        "coinCount":  4,
        "maxRarity":  "SU",
        "width":  38,
        "speed":  1
    },
    {
        "id":  100004,
        "expGain":  225,
        "coinValue":  100,
        "hp":  3000,
        "name":  "대왕 유령",
        "type":  "ghostBoss",
        "equipDropChance":  0.5,
        "damage":  50,
        "height":  230,
        "isHpBig":  true,
        "coinCount":  50,
        "maxRarity":  "SU",
        "width":  190,
        "speed":  1
    },
    {
        "id":  100005,
        "expGain":  45,
        "coinValue":  20,
        "hp":  60,
        "name":  "노예 유령",
        "type":  "ghostSlave",
        "equipDropChance":  0.5,
        "damage":  20,
        "height":  46,
        "isHpBig":  false,
        "coinCount":  4,
        "maxRarity":  "SU",
        "width":  38,
        "speed":  1
    }
];

