// Item Data (Auto Generated)
const ITEM_DEFINITIONS = {
    "400001":  {
                   "id":  400001,
                   "type":  "potion",
                   "name":  "소형 체력 포션",
                   "rarity":  "D",
                   "description":  "체력을 소량 회복한다",
                   "effect":  "healHp",
                   "value":  30,
                   "stackMax":  99,
                   "dropWeight":  100,
                   "color":  "#FF6B6B",
                   "returnGoldValue":  5
               },
    "400002":  {
                   "id":  400002,
                   "type":  "potion",
                   "name":  "중형 체력 포션",
                   "rarity":  "C",
                   "description":  "체력을 회복한다",
                   "effect":  "healHp",
                   "value":  80,
                   "stackMax":  99,
                   "dropWeight":  100,
                   "color":  "#FF4444",
                   "returnGoldValue":  15
               },
    "400003":  {
                   "id":  400003,
                   "type":  "potion",
                   "name":  "대형 체력 포션",
                   "rarity":  "B",
                   "description":  "체력을 대량 회복한다",
                   "effect":  "healHp",
                   "value":  200,
                   "stackMax":  99,
                   "dropWeight":  100,
                   "color":  "#FF0000",
                   "returnGoldValue":  50
               },
    "400004":  {
                   "id":  400004,
                   "type":  "potion",
                   "name":  "고급 체력 포션",
                   "rarity":  "A",
                   "description":  "체력을 크게 회복한다",
                   "effect":  "healHp",
                   "value":  500,
                   "stackMax":  99,
                   "dropWeight":  100,
                   "color":  "#DC143C",
                   "returnGoldValue":  150
               },
    "400005":  {
                   "id":  400005,
                   "type":  "potion",
                   "name":  "특급 체력 포션",
                   "rarity":  "S",
                   "description":  "체력을 매우 크게 회복한다",
                   "effect":  "healHp",
                   "value":  1000,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#FF1493",
                   "returnGoldValue":  500
               },
    "400006":  {
                   "id":  400006,
                   "type":  "potion",
                   "name":  "전설의 포션",
                   "rarity":  "SS",
                   "description":  "체력을 대폭 회복한다",
                   "effect":  "healHp",
                   "value":  2000,
                   "stackMax":  30,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  1500
               },
    "400007":  {
                   "id":  400007,
                   "type":  "potion",
                   "name":  "드래곤 포션",
                   "rarity":  "SR",
                   "description":  "드래곤의 힘이 담긴 포션",
                   "effect":  "healHp",
                   "value":  5000,
                   "stackMax":  20,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  5000
               },
    "400008":  {
                   "id":  400008,
                   "type":  "potion",
                   "name":  "엘릭서",
                   "rarity":  "SU",
                   "description":  "체력을 완전히 회복한다",
                   "effect":  "healHpFull",
                   "value":  100,
                   "stackMax":  10,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  15000
               },
    "400101":  {
                   "id":  400101,
                   "type":  "potion",
                   "name":  "민첩의 물약",
                   "rarity":  "D",
                   "description":  "일시적으로 이동속도 소폭 증가",
                   "effect":  "buffSpeed",
                   "value":  1.1,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#87CEEB",
                   "returnGoldValue":  5
               },
    "400102":  {
                   "id":  400102,
                   "type":  "potion",
                   "name":  "민첩의 물약 II",
                   "rarity":  "C",
                   "description":  "일시적으로 이동속도 증가",
                   "effect":  "buffSpeed",
                   "value":  1.2,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#00BFFF",
                   "returnGoldValue":  15
               },
    "400103":  {
                   "id":  400103,
                   "type":  "potion",
                   "name":  "민첩의 물약 III",
                   "rarity":  "B",
                   "description":  "일시적으로 이동속도 크게 증가",
                   "effect":  "buffSpeed",
                   "value":  1.3,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#00CED1",
                   "returnGoldValue":  50
               },
    "400104":  {
                   "id":  400104,
                   "type":  "potion",
                   "name":  "민첩의 물약 IV",
                   "rarity":  "A",
                   "description":  "일시적으로 이동속도 대폭 증가",
                   "effect":  "buffSpeed",
                   "value":  1.5,
                   "stackMax":  30,
                   "dropWeight":  100,
                   "color":  "#00FFFF",
                   "returnGoldValue":  150
               },
    "400105":  {
                   "id":  400105,
                   "type":  "potion",
                   "name":  "질풍의 물약",
                   "rarity":  "S",
                   "description":  "바람처럼 빠르게 이동",
                   "effect":  "buffSpeed",
                   "value":  1.8,
                   "stackMax":  20,
                   "dropWeight":  100,
                   "color":  "#00FF7F",
                   "returnGoldValue":  500
               },
    "400106":  {
                   "id":  400106,
                   "type":  "potion",
                   "name":  "섬광의 물약",
                   "rarity":  "SS",
                   "description":  "번개처럼 빠르게 이동",
                   "effect":  "buffSpeed",
                   "value":  2,
                   "stackMax":  10,
                   "dropWeight":  100,
                   "color":  "#FFFF00",
                   "returnGoldValue":  1500
               },
    "400107":  {
                   "id":  400107,
                   "type":  "potion",
                   "name":  "순간이동 물약",
                   "rarity":  "SR",
                   "description":  "순간적으로 엄청난 속도",
                   "effect":  "buffSpeed",
                   "value":  2.5,
                   "stackMax":  5,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  5000
               },
    "400108":  {
                   "id":  400108,
                   "type":  "potion",
                   "name":  "시간의 물약",
                   "rarity":  "SU",
                   "description":  "시간을 초월한 속도",
                   "effect":  "buffSpeed",
                   "value":  3,
                   "stackMax":  3,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  15000
               },
    "400201":  {
                   "id":  400201,
                   "type":  "scroll",
                   "name":  "귀환 주문서",
                   "rarity":  "D",
                   "description":  "마을로 귀환한다",
                   "effect":  "teleportTown",
                   "value":  0,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#F5F5DC",
                   "returnGoldValue":  5
               },
    "400202":  {
                   "id":  400202,
                   "type":  "scroll",
                   "name":  "순간이동 주문서",
                   "rarity":  "C",
                   "description":  "지정 위치로 이동",
                   "effect":  "teleport",
                   "value":  0,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#87CEEB",
                   "returnGoldValue":  15
               },
    "400203":  {
                   "id":  400203,
                   "type":  "scroll",
                   "name":  "식별 주문서",
                   "rarity":  "B",
                   "description":  "미확인 아이템을 식별한다",
                   "effect":  "identify",
                   "value":  0,
                   "stackMax":  99,
                   "dropWeight":  100,
                   "color":  "#DEB887",
                   "returnGoldValue":  50
               },
    "400204":  {
                   "id":  400204,
                   "type":  "scroll",
                   "name":  "축복 주문서",
                   "rarity":  "A",
                   "description":  "장비에 축복을 부여한다",
                   "effect":  "bless",
                   "value":  0,
                   "stackMax":  30,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  150
               },
    "400205":  {
                   "id":  400205,
                   "type":  "scroll",
                   "name":  "강화 주문서",
                   "rarity":  "S",
                   "description":  "장비를 강화한다",
                   "effect":  "enhance",
                   "value":  1,
                   "stackMax":  20,
                   "dropWeight":  100,
                   "color":  "#9370DB",
                   "returnGoldValue":  500
               },
    "400206":  {
                   "id":  400206,
                   "type":  "scroll",
                   "name":  "고급 강화 주문서",
                   "rarity":  "SS",
                   "description":  "장비를 안전하게 강화한다",
                   "effect":  "enhanceSafe",
                   "value":  1,
                   "stackMax":  10,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  1500
               },
    "400207":  {
                   "id":  400207,
                   "type":  "scroll",
                   "name":  "부활 주문서",
                   "rarity":  "SR",
                   "description":  "사망시 즉시 부활한다",
                   "effect":  "revive",
                   "value":  100,
                   "stackMax":  5,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  5000
               },
    "400208":  {
                   "id":  400208,
                   "type":  "scroll",
                   "name":  "기적의 주문서",
                   "rarity":  "SU",
                   "description":  "모든 효과를 부여한다",
                   "effect":  "miracle",
                   "value":  0,
                   "stackMax":  3,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  15000
               },
    "400301":  {
                   "id":  400301,
                   "type":  "food",
                   "name":  "빵",
                   "rarity":  "D",
                   "description":  "허기를 채워준다",
                   "effect":  "healHp",
                   "value":  15,
                   "stackMax":  99,
                   "dropWeight":  100,
                   "color":  "#DEB887",
                   "returnGoldValue":  3
               },
    "400302":  {
                   "id":  400302,
                   "type":  "food",
                   "name":  "고기구이",
                   "rarity":  "C",
                   "description":  "맛있는 고기 요리",
                   "effect":  "healHp",
                   "value":  50,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#CD853F",
                   "returnGoldValue":  10
               },
    "400303":  {
                   "id":  400303,
                   "type":  "food",
                   "name":  "스테이크",
                   "rarity":  "B",
                   "description":  "풍미 가득한 스테이크",
                   "effect":  "healHp",
                   "value":  120,
                   "stackMax":  50,
                   "dropWeight":  100,
                   "color":  "#8B4513",
                   "returnGoldValue":  35
               },
    "400304":  {
                   "id":  400304,
                   "type":  "food",
                   "name":  "고급 정찬",
                   "rarity":  "A",
                   "description":  "귀족의 식사",
                   "effect":  "healHp",
                   "value":  300,
                   "stackMax":  30,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  100
               },
    "400305":  {
                   "id":  400305,
                   "type":  "food",
                   "name":  "용의 고기",
                   "rarity":  "S",
                   "description":  "드래곤 고기 요리",
                   "effect":  "healHp",
                   "value":  600,
                   "stackMax":  20,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  350
               },
    "400306":  {
                   "id":  400306,
                   "type":  "food",
                   "name":  "신들의 음식",
                   "rarity":  "SS",
                   "description":  "신성한 요리",
                   "effect":  "healHp",
                   "value":  1200,
                   "stackMax":  10,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  1000
               },
    "400307":  {
                   "id":  400307,
                   "type":  "food",
                   "name":  "불멸의 과일",
                   "rarity":  "SR",
                   "description":  "불멸의 나무 열매",
                   "effect":  "healHp",
                   "value":  2500,
                   "stackMax":  5,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  3500
               },
    "400308":  {
                   "id":  400308,
                   "type":  "food",
                   "name":  "왕의 만찬",
                   "rarity":  "SU",
                   "description":  "최고급 요리",
                   "effect":  "healHpFull",
                   "value":  100,
                   "stackMax":  3,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  10000
               },
    "400401":  {
                   "id":  400401,
                   "type":  "bomb",
                   "name":  "수류탄",
                   "rarity":  "D",
                   "description":  "범위 피해를 준다",
                   "effect":  "areaDamage",
                   "value":  30,
                   "stackMax":  30,
                   "dropWeight":  100,
                   "color":  "#808080",
                   "returnGoldValue":  8
               },
    "400402":  {
                   "id":  400402,
                   "type":  "bomb",
                   "name":  "화염병",
                   "rarity":  "C",
                   "description":  "화염 범위 피해",
                   "effect":  "areaDamage",
                   "value":  60,
                   "stackMax":  30,
                   "dropWeight":  100,
                   "color":  "#FF4500",
                   "returnGoldValue":  25
               },
    "400403":  {
                   "id":  400403,
                   "type":  "bomb",
                   "name":  "얼음 폭탄",
                   "rarity":  "B",
                   "description":  "적을 동결시킨다",
                   "effect":  "freeze",
                   "value":  3,
                   "stackMax":  20,
                   "dropWeight":  100,
                   "color":  "#00BFFF",
                   "returnGoldValue":  80
               },
    "400404":  {
                   "id":  400404,
                   "type":  "bomb",
                   "name":  "번개 폭탄",
                   "rarity":  "A",
                   "description":  "번개 범위 피해",
                   "effect":  "areaDamage",
                   "value":  150,
                   "stackMax":  20,
                   "dropWeight":  100,
                   "color":  "#FFFF00",
                   "returnGoldValue":  250
               },
    "400405":  {
                   "id":  400405,
                   "type":  "bomb",
                   "name":  "독 폭탄",
                   "rarity":  "S",
                   "description":  "독 범위 피해",
                   "effect":  "poison",
                   "value":  5,
                   "stackMax":  15,
                   "dropWeight":  100,
                   "color":  "#32CD32",
                   "returnGoldValue":  800
               },
    "400406":  {
                   "id":  400406,
                   "type":  "bomb",
                   "name":  "용암 폭탄",
                   "rarity":  "SS",
                   "description":  "용암 범위 피해",
                   "effect":  "areaDamage",
                   "value":  400,
                   "stackMax":  10,
                   "dropWeight":  100,
                   "color":  "#FF4500",
                   "returnGoldValue":  2500
               },
    "400407":  {
                   "id":  400407,
                   "type":  "bomb",
                   "name":  "드래곤 브레스",
                   "rarity":  "SR",
                   "description":  "드래곤의 숨결",
                   "effect":  "areaDamage",
                   "value":  800,
                   "stackMax":  5,
                   "dropWeight":  100,
                   "color":  "#FF4466",
                   "returnGoldValue":  8000
               },
    "400408":  {
                   "id":  400408,
                   "type":  "bomb",
                   "name":  "심판의 폭탄",
                   "rarity":  "SU",
                   "description":  "신의 심판",
                   "effect":  "areaDamage",
                   "value":  2000,
                   "stackMax":  3,
                   "dropWeight":  100,
                   "color":  "#FFD700",
                   "returnGoldValue":  25000
               }
};
